[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[build]]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[[deploy]]
  region = "us-west2"
  runtime = "V2"
  numReplicas = 1
  startCommand = "npx serve -s dist"
  sleepApplication = false
  multiRegionConfig = { us_west2 = { numReplicas = 1 } }  # Corrected inline table syntax
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
